# coding: utf-8


class LMResonseInterface():
  """
  This is the callback interface for handling the response.
  End user can create his own class using this one to get the response status.
  """

  def __init__(self):
    super(LMResonseInterface, self).__init__()

  @classmethod
  def success_callback(self, request, response, status, request_id):
    """
    This callback gets invoked for successful response from the end REST endpoint.

    Args:
        request (dict): The json payload send to REST endpoint.
        response (dict): Response received from the REST endpoint.
        status (int): HTTP status code.
        request_id (str): Unique request id generated by Rest endpoint.
    """
    pass

  @classmethod
  def error_callback(self, request, response, status, request_id, reason):
    """
    This callback gets invoked for any error or exception from the end REST endpoint.

    Args:
        request (dict): The json payload send to REST endpoint.
        response (dict): Response received from the REST endpoint.
        status (int): HTTP status code.
        request_id (str): Unique request id generated by Rest endpoint.
        reason (str): The reason for error.
    """
    pass
